Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/vscode/.local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/vscode/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/vscode/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/vscode/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/vscode/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Modules
import pandas as pd
import random
import re
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns
import spacy
from spacy import displacy
import dacy
import json
import netwulf
import networkx as nx

# Imports
from nlp_utils import *
from pathlib import Path
import powerlaw
from network_utils import louvain_based_communities_randomized
from networkx import edge_boundary
from difflib import SequenceMatcher
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import defaultdict, Counter
from wordcloud import WordCloud
import os

# Configuration
spacy.require_gpu() # run SpaCy GPU-accelerated
sns.set_theme()

# Ignore warnings for prettier output
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
warnings.simplefilter(action="ignore", category=UserWarning)
------------------

----- stderr -----
/home/vscode/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 16[0m
[1;32m     13[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mnetworkx[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mnx[39;00m
[1;32m     15[0m [38;5;66;03m# Imports[39;00m
[0;32m---> 16[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mnlp_utils[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     17[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mpathlib[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Path
[1;32m     18[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpowerlaw[39;00m

[0;31mModuleNotFoundError[0m: No module named 'nlp_utils'

